[package]
name = "joan-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
joan-bytecode = { path = "../joan-bytecode" }
joan-canonical = { path = "../joan-canonical" }
joan-lattice = { path = "../joan-lattice" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
joan-compiler = { path = "../joan-compiler" }

[lints]
workspace = true
