[package]
name = "joan-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
joan-canonical = { path = "../joan-canonical" }
joan-compiler = { path = "../joan-compiler" }
joan-instruction = { path = "../joan-instruction" }
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
