[package]
name = "joan-bytecode"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
joan-ast = { path = "../joan-ast" }
joan-canonical = { path = "../joan-canonical" }
joan-check = { path = "../joan-check" }
joan-identity = { path = "../joan-identity" }
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
