[package]
name = "joan-abi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
authors.workspace = true
publish.workspace = true

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
joan-bytecode = { path = "../joan-bytecode" }
joan-lattice = { path = "../joan-lattice" }

[dev-dependencies]
jsonschema.workspace = true
joan-compiler = { path = "../joan-compiler" }
proptest.workspace = true
serde_json.workspace = true

[lints.rust]
unsafe_code = "warn"
missing_docs = "warn"
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
